routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth.login');
});

Route::get('/login-now', function () {
    return view('_layouts.login');
});

// Authentication Routes...
Route::get('/login', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('/login', 'Auth\LoginController@login');
Route::get('/logout', function () {

    Auth::guard()->logout();

    Session::flush();

    Session::regenerate();

    return redirect('/');

})->name('user.logout');

// Password Reset Routes...
Route::get('/password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
Route::post('/password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
Route::get('/password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
Route::post('/password/reset', 'Auth\ResetPasswordController@reset');

Route::get('/home', 'HomeController@index')->name('home');

//CLIENT PAGES
Route::group(['middleware' => ['client'], 'prefix' => 'client', 'as' => 'client.'], function () {

    Route::get('/', 'Client\HomeController@index')->name('index');
    Route::get('/profile', 'Client\HomeController@profile')->name('profile');
    Route::post('/update-profile', 'Client\HomeController@updateProfile')->name('update.profile');
    Route::post('/add-company', 'Client\HomeController@addCompany')->name('add.company');
    Route::post('/company/make-default/{uid}/{id}', 'Client\HomeController@makeDefaultCompany')->name('update.company.defualt');
    Route::post('/company/delete/{id}', 'Client\HomeController@deleteCompany')->name('update.company.delete');
    Route::post('/company/add-user-form/{id}', 'Client\HomeController@addUserCompanyForm')->name('company.add.user.form');
    Route::post('/company/add-user', 'Client\HomeController@addUserCompany')->name('company.add.user');

    //NOTIFICATION PROCESS
    Route::post('/notification/update/{cid}/{type}', 'Client\NotificationController@update')->name('update.notification');

    //MESSAGES
    Route::get('/messages/{type}', 'Client\MessagesController@index')->name('messages');
    Route::get('/message/{slug}', 'Client\MessagesController@show')->name('show.message');
    Route::post('/message/reply-message-form/{id}', 'Client\MessagesController@getReplyForm')->name('message.reply.form');
    Route::post('/message/reply', 'Client\MessagesController@reply')->name('message.reply');
    Route::post('/message/create', 'Client\MessagesController@store')->name('message.create');
    Route::post('/message/delete/{id}', 'Client\MessagesController@delete')->name('message.delete');
    Route::post('/message/restore/{id}', 'Client\MessagesController@restore')->name('message.restore');
    Route::post('/message/read/{id}', 'Client\MessagesController@read')->name('message.read');
    Route::post('/message/unread/{id}', 'Client\MessagesController@unread')->name('message.unread');
    Route::post('/message/trash/{id}', 'Client\MessagesController@trash')->name('message.trash');

    //BOOKING PROCESS
    Route::resource('/bookings', 'Client\BookingController');

    //MODELS
    Route::get('/models', 'Client\ModelController@index')->name('models');
    Route::post('/model/create', 'Client\ModelController@create')->name('model.create');
    Route::post('/model-fleet-create-form/{id}', 'Client\ModelController@getFleetForm')->name('create.model.fleet.form');
    Route::post('/model-edit-form/{id}', 'Client\ModelController@getForm')->name('edit.model.form');
    Route::get('/model/{slug}', 'Client\ModelController@availability')->name('model.availability');
    Route::post('/model/edit', 'Client\ModelController@update')->name('update.model');

    //FLEETS
    Route::get('/fleets', 'Client\FleetController@index')->name('fleets');
    Route::get('/fleet/{slug}', 'Client\FleetController@show')->name('fleet.show');
    Route::post('/fleet/create', 'Client\FleetController@create')->name('fleet.create');
    Route::post('/fleet/add-accessory', 'Client\FleetController@addAccessory')->name('fleet.add.accessory');
    Route::post('/fleet/update-accessory', 'Client\FleetController@updateAccessory')->name('fleet.update.accessory');
    Route::post('/fleet/add-note', 'Client\FleetController@addNote')->name('fleet.add.note');
    Route::post('/fleet/update-note', 'Client\FleetController@updateNote')->name('fleet.update.note');
    Route::post('/fleet-edit-form/{id}', 'Client\FleetController@editForm')->name('edit.fleet.form');
    Route::post('/fleet/edit', 'Client\FleetController@update')->name('update.fleet');
    Route::post('/fleet-book-form/{id}', 'Client\FleetController@bookingForm')->name('book.fleet.form');
    Route::post('/fleet/book', 'Client\FleetController@book')->name('fleet.book');
    Route::post('/fleet-collected-form/{id}/{bid}', 'Client\FleetController@collectedForm')->name('collected.fleet.form');
    Route::post('/fleet/collected', 'Client\FleetController@collected')->name('fleet.collected');
    Route::post('/fleet-returned-form/{id}/{bid}', 'Client\FleetController@returnedForm')->name('returned.fleet.form');
    Route::post('/fleet/returned', 'Client\FleetController@returned')->name('fleet.returned');
    Route::post('/fleet-status-form/{id}', 'Client\FleetController@statusForm')->name('status.fleet.form');
    Route::post('/fleet/status', 'Client\FleetController@updateStatus')->name('fleet.status');
    Route::post('/fleet-return-form/{id}', 'Client\FleetController@returnForm')->name('return.fleet.form');
    Route::post('/fleet/return', 'Client\FleetController@returnItem')->name('fleet.return');

    Route::post('/fleet-available-form/{id}', 'Client\FleetController@availableForm')->name('available.fleet.form');
    Route::post('/fleet/available', 'Client\FleetController@makeAvailable')->name('fleet.available');

    Route::post('/fleet-information-form/{id}', 'Client\FleetController@informationForm')->name('information.fleet.form');
    Route::post('/fleet/delete/{id}', 'Client\FleetController@delete')->name('fleet.delete');

    //Borrowers
    Route::get('/borrowers/{cid}', 'Client\BorrowerController@index')->name('borrowers.index');
    Route::post('/borrower-form/{bid}', 'Client\BorrowerController@editForm')->name('borrower.form');
    Route::post('/borrower-add', 'Client\BorrowerController@store')->name('borrower.create');
    Route::post('/borrower-update', 'Client\BorrowerController@update')->name('borrower.update');

    //LOG BACK AS ADMIN
    Route::get('users/logback-as/{id}',  'Admin\UserController@logbackAs')->name('logback.as');

});

//ADMIN PAGES
Route::group(['middleware' => ['admin'], 'prefix' => 'admin', 'as' => 'admin.'], function () {

    Route::get('/', 'Admin\HomeController@index')->name('index');
    Route::get('/clients', 'Admin\HomeController@clients')->name('clients');

    //USERS
    Route::get('/users', 'Admin\UserController@index')->name('users');
    Route::post('/user-form/{id}', 'Admin\UserController@getUserForm')->name('user.info');
    Route::post('/user-role-form/{id}', 'Admin\UserController@getRoleForm')->name('user.role.info');
    Route::post('/user-permissions-form/{id}', 'Admin\UserController@getPermissionsForm')->name('user.permission.info');
    Route::post('/user-delete-form/{id}', 'Admin\UserController@getDeleteForm')->name('user.delete.info');
    Route::post('/user/info', 'Admin\UserController@updateUser')->name('update.user');
    Route::post('/user/role', 'Admin\UserController@updateRole')->name('update.role');
    Route::post('/user/permissions', 'Admin\UserController@updatePermissions')->name('update.permissions');
    Route::post('/user/delete', 'Admin\UserController@delete')->name('user.delete');
    Route::post('/user/register', 'Admin\UserController@store')->name('register.user');

    //COMPANIES
    Route::get('/companies', 'Admin\CompanyController@index')->name('companies');
    Route::post('/company/register', 'Admin\CompanyController@store')->name('register.company');
    Route::post('/company-user-form/{id}', 'Admin\CompanyController@companyUsersForm')->name('company.users.form');
    Route::post('/company-form/{id}', 'Admin\CompanyController@getForm')->name('company.info');
    Route::post('/company/update', 'Admin\CompanyController@update')->name('update.company');
    Route::post('/company-delete-form/{id}', 'Admin\CompanyController@getDeleteForm')->name('user.delete.info');
    Route::post('/company/delete', 'Admin\CompanyController@delete')->name('delete.company');

    //BORROWERS
    Route::get('/borrowers', 'Admin\BorrowerController@index')->name('borrowers');
    Route::post('/borrower/create', 'Admin\BorrowerController@create')->name('borrower.create');
    Route::post('/borrower-form/{id}', 'Admin\BorrowerController@getForm')->name('borrower.info');
    Route::post('/borrower/update', 'Admin\BorrowerController@update')->name('update.borrower');
    Route::post('/borrower-delete-form/{id}', 'Admin\BorrowerController@getDeleteForm')->name('borrower.delete.info');
    Route::post('/borrower/delete', 'Admin\BorrowerController@delete')->name('delete.borrower');

    //BOOKING TYPE
    Route::get('/bookingtypes', 'Admin\BookingTypeController@index')->name('bookingtypes');
    Route::post('/bookingtype/create', 'Admin\BookingTypeController@create')->name('bookingtype.create');
    Route::post('/bookingtype-form/{id}', 'Admin\BookingTypeController@getForm')->name('bookingtype.info');
    Route::post('/bookingtype/update', 'Admin\BookingTypeController@update')->name('update.bookingtype');

app/Client.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Client extends Model
{
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'firstname', 'lastname', 'user_id', 'image','lastname', 'mobile', 'phone', 'profile'
    ];

    public function user()
    {
        return $this->belongsTo(User::class, 'user_id');
    }

    public function company()
    {
        return $this->hasOne(Company::class, 'client_id')->where(['default' => 1]);
    }

    public function userCompany()
    {
        return $this->belongsToMany(Company::class, 'client_company');
    }

    public function companies()
    {
        return $this->hasMany(Company::class, 'client_id');
    }

    public function unreadMessages()
    {
        return $this->hasMany(Message::class, 'client_id')->where(['read' => 0]);
    }

    public function messages()
    {
        return $this->hasMany(Message::class, 'client_id');
    }

    public function notification()
    {
        return $this->hasOne(Notification::class, 'client_id');
    }

    public function getImageUrlAttribute($value) {

        $imageUrl = "";

        if (!is_null($this->image) && $this->image != '') {
            $imagePath = public_path() . "/images/clients/" . $this->image;
            if (file_exists($imagePath)) {
                $imageUrl = asset("/images/clients/" . $this->image);
            } else {
                $imageUrl = asset("/images/no-image.jpg");
            }
        } else {
            $imageUrl = asset("/images/no-image.jpg");
        }

        return $imageUrl;
    }

}

app/Http/Controllers/Client/BookingController.php
<?php

namespace App\Http\Controllers\Client;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

use App\Booking;

class BookingController extends Controller
{
    public function index()
    {
        $bookings = Booking::all();
        //dd($bookings);
        return view('client.bookings', compact('bookings'));
    }


    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $slug
     * @return \Illuminate\Http\Response
     */
    public function show($slug)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }

}

app/Http/Controllers/Client/NotificationController.php
<?php

namespace App\Http\Controllers\Client;

use App\Notification;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

use App\User;

class NotificationController extends Controller
{
    /**
     * Update notification from settings.
    */
    public function update($cid, $type)
    {
        $notification = Notification::where(['client_id' => $cid])->first();
        $notification->{$type} = $notification->{$type} == 1 ? 0 : 1;
        $notification->save();
    }
}

resources/views/_templates/client/bookings.blade.php
<div class="row bg-title">
    <div class="col-lg-3 col-md-4 col-sm-4 col-xs-12">
        <h4 class="page-title pull-left">Bookings</h4>
    </div>
    <div class="col-lg-9 col-sm-8 col-md-8 col-xs-12">
        <ol class="breadcrumb">
            <li><a href="{{ route('client.index') }}"><i class="fa fa-dashboard"></i> Dashboard</a></li>
            <li class="active"><i class="mdi mdi-book-open-variant"></i> Bookings</li>
        </ol>
    </div>
</div>

resources/views/_templates/client/borrowers.blade.php
<div class="row bg-title">
    <div class="col-lg-3 col-md-4 col-sm-4 col-xs-12">
        <h4 class="page-title pull-left">Borrowers</h4>
        @if(Request::is('client/borrowers/*'))
            <div class="pull-right">
                <button data-toggle="modal" data-target="#modal_add" class="btn btn-block btn-success btn-rounded">Add New Borrower </button>
            </div>
        @endif
    </div>
    <div class="col-lg-9 col-sm-8 col-md-8 col-xs-12">
        <ol class="breadcrumb">
            <li><a href="{{ route('client.index') }}"><i class="fa fa-dashboard"></i> Dashboard</a></li>
            @if(Request::is('client/borrower/*'))
                <li><a href="{{ route('client.borrowers') }}"><i class="mdi mdi-alphabetical"></i> Borrowers</a></li>
                <li class="active"><i class="mdi mdi-alpha"></i> Name: <strong></strong></li>
            @else
                <li class="active"><i class="mdi mdi-alphabetical"></i> Fleets</li>
            @endif
        </ol>
    </div>
</div>

resources/views/_templates/client/dashboard-header.blade.php
<div class="row bg-title">
    <div class="col-lg-3 col-md-4 col-sm-4 col-xs-12">
        <h4 class="page-title">Dashboard</h4> </div>
    <div class="col-lg-9 col-sm-8 col-md-8 col-xs-12">

        <ol class="breadcrumb">
            <li><i class="fa fa-dashboard"></i> Dashboard</li>
        </ol>
    </div>

</div>

resources/views/_templates/client/fleet-header.blade.php
<div class="row bg-title">
    <div class="col-lg-3 col-md-4 col-sm-4 col-xs-12">
        <h4 class="page-title pull-left">Fleet</h4>
        @if(Request::is('client/fleets'))
        <div class="pull-right">
          <button data-toggle="modal" data-target="#modal_add" class="btn btn-block btn-success btn-rounded">Add New Fleet </button>
        </div>
       @endif
    </div>
    <div class="col-lg-9 col-sm-8 col-md-8 col-xs-12">
        <ol class="breadcrumb">
            <li><a href="{{ route('client.index') }}"><i class="fa fa-dashboard"></i> Dashboard</a></li>
            @if(Request::is('client/fleet/*'))
                <li><a href="{{ route('client.fleets') }}"><i class="mdi mdi-alphabetical"></i> Fleets</a></li>
                <li class="active"><i class="mdi mdi-alpha"></i> Fleet: <strong>{{ $fleet->reg_number }}</strong></li>
            @else
                <li class="active"><i class="mdi mdi-alphabetical"></i> Fleets</li>
            @endif
        </ol>
    </div>
</div>

resources/views/_templates/client/message-header.blade.php
<div class="row bg-title">
    <div class="col-lg-3 col-md-4 col-sm-4 col-xs-12">
        <h4 class="page-title">Message Mailbox</h4> </div>
    <div class="col-lg-9 col-sm-8 col-md-8 col-xs-12">
        <ol class="breadcrumb">
            <li><a href="{{ route('client.index') }}"><i class="fa fa-dashboard"></i> Dashboard</a></li>
            @if(Request::is('client/message/*'))
                <li><a href="{{ route('client.messages', 'inbox') }}"><i class="fa fa-envelope"></i> Messages</a></li>
                <li class="active"><i class="fa fa-envelope-o"></i> Message</li>
            @else
                <li class="active"><i class="fa fa-envelope"></i> Messages</li>
            @endif

        </ol>
    </div>
</div>

resources/views/_templates/client/model-header.blade.php
<div class="row bg-title">
    <div class="col-lg-3 col-md-4 col-sm-4 col-xs-12">
        <h4 class="page-title pull-left">Models</h4>
        @if(Request::is('client/models'))
        <div class="pull-right">
            <button data-toggle="modal" data-target="#modal_add" class="btn btn-block btn-success btn-rounded">Add New Model</button>
        </div>
        @endif
    </div>
    <div class="col-lg-9 col-sm-8 col-md-8 col-xs-12">
        <ol class="breadcrumb">
            <li><a href="{{ route('client.index') }}"><i class="fa fa-dashboard"></i> Dashboard</a></li>
            @if(Request::is('client/models/*'))
                <li><a href="{{ route('client.models') }}"><i class="mdi mdi-engine"></i> Models</a></li>
                <li class="active"><i class="mdi mdi-engine-outline"></i> Model</li>
            @elseif(Request::is('client/model/*'))
                <li><a href="{{ route('client.models') }}"><i class="mdi mdi-engine"></i> Models</a></li>
                <li class="active"><i class="mdi mdi-calendar-clock"></i> Model Availability: <strong>{{ $model->name }}</strong></li>
            @else
                <li class="active"><i class="mdi mdi-engine"></i> Models</li>
            @endif

        </ol>
    </div>
</div>

resources/views/_templates/client/profile-header.blade.php
<div class="row bg-title">
    <div class="col-lg-3 col-md-4 col-sm-4 col-xs-12">
        <h4 class="page-title">Profile page</h4> </div>
    <div class="col-lg-9 col-sm-8 col-md-8 col-xs-12">

         <ol class="breadcrumb">
            <li><a href="{{ route('client.index') }}"><i class="fa fa-dashboard"></i> Dashboard</a></li>
            <li class="active"><i class="fa fa-user"></i> Profile page</li>
        </ol>
    </div>
</div>