routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth.login');
});

Route::get('/login-now', function () {
    return view('_layouts.login');
});

// Authentication Routes...
Route::get('/login', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('/login', 'Auth\LoginController@login');
Route::get('/logout', function () {

    Auth::guard()->logout();

    Session::flush();

    Session::regenerate();

    return redirect('/');

})->name('user.logout');

// Password Reset Routes...
Route::get('/password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
Route::post('/password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
Route::get('/password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
Route::post('/password/reset', 'Auth\ResetPasswordController@reset');

Route::get('/home', 'HomeController@index')->name('home');

//CLIENT PAGES
Route::group(['middleware' => ['client'], 'prefix' => 'client', 'as' => 'client.'], function () {

    Route::get('/', 'Client\HomeController@index')->name('index');
    Route::get('/profile', 'Client\HomeController@profile')->name('profile');
    Route::post('/update-profile', 'Client\HomeController@updateProfile')->name('update.profile');
    Route::post('/add-company', 'Client\HomeController@addCompany')->name('add.company');
    Route::post('/company/make-default/{uid}/{id}', 'Client\HomeController@makeDefaultCompany')->name('update.company.defualt');
    Route::post('/company/delete/{id}', 'Client\HomeController@deleteCompany')->name('update.company.delete');
    Route::post('/company/add-user-form/{id}', 'Client\HomeController@addUserCompanyForm')->name('company.add.user.form');
    Route::post('/company/add-user', 'Client\HomeController@addUserCompany')->name('company.add.user');

    //NOTIFICATION PROCESS
    Route::post('/notification/update/{cid}/{type}', 'Client\NotificationController@update')->name('update.notification');

    //MESSAGES
    Route::get('/messages/{type}', 'Client\MessagesController@index')->name('messages');
    Route::get('/message/{slug}', 'Client\MessagesController@show')->name('show.message');
    Route::post('/message/reply-message-form/{id}', 'Client\MessagesController@getReplyForm')->name('message.reply.form');
    Route::post('/message/reply', 'Client\MessagesController@reply')->name('message.reply');
    Route::post('/message/create', 'Client\MessagesController@store')->name('message.create');
    Route::post('/message/delete/{id}', 'Client\MessagesController@delete')->name('message.delete');
    Route::post('/message/restore/{id}', 'Client\MessagesController@restore')->name('message.restore');
    Route::post('/message/read/{id}', 'Client\MessagesController@read')->name('message.read');
    Route::post('/message/unread/{id}', 'Client\MessagesController@unread')->name('message.unread');
    Route::post('/message/trash/{id}', 'Client\MessagesController@trash')->name('message.trash');

    //BOOKING PROCESS
    Route::resource('/bookings', 'Client\BookingController');

    //MODELS
    Route::get('/models', 'Client\ModelController@index')->name('models');
    Route::post('/model/create', 'Client\ModelController@create')->name('model.create');
    Route::post('/model-fleet-create-form/{id}', 'Client\ModelController@getFleetForm')->name('create.model.fleet.form');
    Route::post('/model-edit-form/{id}', 'Client\ModelController@getForm')->name('edit.model.form');
    Route::get('/model/{slug}', 'Client\ModelController@availability')->name('model.availability');
    Route::post('/model/edit', 'Client\ModelController@update')->name('update.model');

    //FLEETS
    Route::get('/fleets', 'Client\FleetController@index')->name('fleets');
    Route::get('/fleet/{slug}', 'Client\FleetController@show')->name('fleet.show');
    Route::post('/fleet/create', 'Client\FleetController@create')->name('fleet.create');
    Route::post('/fleet/add-accessory', 'Client\FleetController@addAccessory')->name('fleet.add.accessory');
    Route::post('/fleet/update-accessory', 'Client\FleetController@updateAccessory')->name('fleet.update.accessory');
    Route::post('/fleet/add-note', 'Client\FleetController@addNote')->name('fleet.add.note');
    Route::post('/fleet/update-note', 'Client\FleetController@updateNote')->name('fleet.update.note');
    Route::post('/fleet-edit-form/{id}', 'Client\FleetController@editForm')->name('edit.fleet.form');
    Route::post('/fleet/edit', 'Client\FleetController@update')->name('update.fleet');
    Route::post('/fleet-book-form/{id}', 'Client\FleetController@bookingForm')->name('book.fleet.form');
    Route::post('/fleet/book', 'Client\FleetController@book')->name('fleet.book');
    Route::post('/fleet-collected-form/{id}/{bid}', 'Client\FleetController@collectedForm')->name('collected.fleet.form');
    Route::post('/fleet/collected', 'Client\FleetController@collected')->name('fleet.collected');
    Route::post('/fleet-returned-form/{id}/{bid}', 'Client\FleetController@returnedForm')->name('returned.fleet.form');
    Route::post('/fleet/returned', 'Client\FleetController@returned')->name('fleet.returned');
    Route::post('/fleet-status-form/{id}', 'Client\FleetController@statusForm')->name('status.fleet.form');
    Route::post('/fleet/status', 'Client\FleetController@updateStatus')->name('fleet.status');
    Route::post('/fleet-return-form/{id}', 'Client\FleetController@returnForm')->name('return.fleet.form');
    Route::post('/fleet/return', 'Client\FleetController@returnItem')->name('fleet.return');

    Route::post('/fleet-available-form/{id}', 'Client\FleetController@availableForm')->name('available.fleet.form');
    Route::post('/fleet/available', 'Client\FleetController@makeAvailable')->name('fleet.available');

    Route::post('/fleet-information-form/{id}', 'Client\FleetController@informationForm')->name('information.fleet.form');
    Route::post('/fleet/delete/{id}', 'Client\FleetController@delete')->name('fleet.delete');

    //Borrowers
    Route::get('/borrowers/{cid}', 'Client\BorrowerController@index')->name('borrowers.index');
    Route::post('/borrower-form/{bid}', 'Client\BorrowerController@editForm')->name('borrower.form');
    Route::post('/borrower-add', 'Client\BorrowerController@store')->name('borrower.create');
    Route::post('/borrower-update', 'Client\BorrowerController@update')->name('borrower.update');

    //LOG BACK AS ADMIN
    Route::get('users/logback-as/{id}',  'Admin\UserController@logbackAs')->name('logback.as');

});

//ADMIN PAGES
Route::group(['middleware' => ['admin'], 'prefix' => 'admin', 'as' => 'admin.'], function () {

    Route::get('/', 'Admin\HomeController@index')->name('index');
    Route::get('/clients', 'Admin\HomeController@clients')->name('clients');

    //USERS
    Route::get('/users', 'Admin\UserController@index')->name('users');
    Route::post('/user-form/{id}', 'Admin\UserController@getUserForm')->name('user.info');
    Route::post('/user-role-form/{id}', 'Admin\UserController@getRoleForm')->name('user.role.info');
    Route::post('/user-permissions-form/{id}', 'Admin\UserController@getPermissionsForm')->name('user.permission.info');
    Route::post('/user-delete-form/{id}', 'Admin\UserController@getDeleteForm')->name('user.delete.info');
    Route::post('/user/info', 'Admin\UserController@updateUser')->name('update.user');
    Route::post('/user/role', 'Admin\UserController@updateRole')->name('update.role');
    Route::post('/user/permissions', 'Admin\UserController@updatePermissions')->name('update.permissions');
    Route::post('/user/delete', 'Admin\UserController@delete')->name('user.delete');
    Route::post('/user/register', 'Admin\UserController@store')->name('register.user');

    //COMPANIES
    Route::get('/companies', 'Admin\CompanyController@index')->name('companies');
    Route::post('/company/register', 'Admin\CompanyController@store')->name('register.company');
    Route::post('/company-user-form/{id}', 'Admin\CompanyController@companyUsersForm')->name('company.users.form');
    Route::post('/company-form/{id}', 'Admin\CompanyController@getForm')->name('company.info');
    Route::post('/company/update', 'Admin\CompanyController@update')->name('update.company');
    Route::post('/company-delete-form/{id}', 'Admin\CompanyController@getDeleteForm')->name('user.delete.info');
    Route::post('/company/delete', 'Admin\CompanyController@delete')->name('delete.company');

    //BORROWERS
    Route::get('/borrowers', 'Admin\BorrowerController@index')->name('borrowers');
    Route::post('/borrower/create', 'Admin\BorrowerController@create')->name('borrower.create');
    Route::post('/borrower-form/{id}', 'Admin\BorrowerController@getForm')->name('borrower.info');
    Route::post('/borrower/update', 'Admin\BorrowerController@update')->name('update.borrower');
    Route::post('/borrower-delete-form/{id}', 'Admin\BorrowerController@getDeleteForm')->name('borrower.delete.info');
    Route::post('/borrower/delete', 'Admin\BorrowerController@delete')->name('delete.borrower');

    //BOOKING TYPE
    Route::get('/bookingtypes', 'Admin\BookingTypeController@index')->name('bookingtypes');
    Route::post('/bookingtype/create', 'Admin\BookingTypeController@create')->name('bookingtype.create');
    Route::post('/bookingtype-form/{id}', 'Admin\BookingTypeController@getForm')->name('bookingtype.info');
    Route::post('/bookingtype/update', 'Admin\BookingTypeController@update')->name('update.bookingtype');

resources/views/_partials/admin/footer.blade.php
<footer class="main-footer">
    <div class="pull-right hidden-xs">
        <b>Version</b> 1.0.0
    </div>
    <strong>Copyright &copy; {{ date('Y') }} <a href="http://www.motocom.co.uk/">MotoCom</a>.</strong> All rights
    reserved.
</footer>

resources/views/_partials/admin/sidebar-left.blade.php
<aside class="main-sidebar">

    <section class="sidebar">

        <ul class="sidebar-menu" data-widget="tree">

            <li class="{{ Request::is('admin') ? 'active' : '' }}">
                <a href="{{ route('admin.index') }}" >
                    <i class="fa fa-dashboard"></i> <span>Dashboard</span>
                </a>
            </li>

            <li class="{{ Request::is('admin/user*') ? 'menu-open active' : '' }}">
                <a href="{{ route('admin.users') }}">
                    <i class="fa fa-users"></i>
                    <span>Users</span>
                </a>
            </li>

            <li class="{{ Request::is('admin/companies*') ? 'menu-open active' : '' }}">
                <a href="{{ route('admin.companies') }}">
                    <i class="fa fa-building"></i>
                    <span>Companies</span>
                </a>
            </li>

            <li class="{{ Request::is('admin/borrowers*') ? 'menu-open active' : '' }}">
                <a href="{{ route('admin.borrowers') }}">
                    <i class="fa fa-sign-out"></i>
                    <span>Borrowers</span>
                </a>
            </li>

            <li class="{{ Request::is('admin/bookingtype*') ? 'menu-open active' : '' }}">
                <a href="{{ route('admin.bookingtypes') }}">
                    <i class="fa fa-bookmark"></i>
                    <span>Booking Type</span>
                </a>
            </li>

            <li class="{{ Request::is('admin/categories*') ? 'menu-open active' : '' }}">
                <a href="{{ route('admin.categories') }}">
                    <i class="fa fa-tags"></i>
                    <span>Category</span>
                </a>
            </li>

            <li class="{{ Request::is('admin/vehicle*') ? 'menu-open active' : '' }}">
                <a href="{{ route('admin.vehicles') }}">
                    <i class="fa fa-bicycle"></i>
                    <span>Models</span>
                </a>
            </li>

            <li class="treeview {{ Request::is('admin/fleet*') ? 'menu-open active' : '' }}">
                <a href="#">
                    <i class="fa fa-cubes"></i>
                    <span>Fleet</span>
                    <span class="pull-right-container">
                    <i class="fa fa-angle-left pull-right"></i>
                    </span>
                </a>
                <ul class="treeview-menu">
                <li class="{{ Request::is('admin/fleets') ? 'active' : '' }}"><a href="{{ route('admin.fleets') }}"><i class="fa fa-circle-o"></i> All</a></li>
                <?php $fleetCompanies = \App\Company::all();?>
                @if($fleetCompanies)
                    @foreach($fleetCompanies as $fc)
                        <li class="{{ Request::is('admin/fleets/'.$fc->slug) ? 'active' : '' }}"><a href="{{ route('admin.fleets.company', $fc->slug) }}"><i class="fa fa-circle-o"></i>{{ $fc->company_name }}</a></li>
                    @endforeach
                @endif

                </ul>
            </li>


            {{--<li class="treeview {{ Request::is('admin/user*') ? 'menu-open active' : '' }}">--}}
                {{--<a href="#">--}}
                    {{--<i class="fa fa-users"></i>--}}
                    {{--<span>Users</span>--}}
                    {{--<span class="pull-right-container">--}}
                        {{--<i class="fa fa-angle-left pull-right"></i>--}}
                    {{--</span>--}}
                {{--</a>--}}
                {{--<ul class="treeview-menu">--}}
                    {{--<li class="{{ Request::is('admin/users') ? 'active' : '' }}"><a href="{{ route('admin.users') }}"><i class="fa fa-circle-o"></i> Users</a></li>--}}
                    {{--<li class="{{ Request::is('admin/user/roles') ? 'active' : '' }}"><a href="{{ route('admin.roles') }}"><i class="fa fa-circle-o"></i> Role</a></li>--}}
                    {{--<li class="{{ Request::is('admin/user/permissions') ? 'active' : '' }}"><a href="{{ route('admin.permissions') }}"><i class="fa fa-circle-o"></i> Permission</a></li>--}}
                {{--</ul>--}}
            {{--</li>--}}

            <li><a href="https://adminlte.io/docs"><i class="fa fa-book"></i> <span>Documentation</span></a></li>
        </ul>
    </section>

</aside>

resources/views/_partials/admin/sidebar-right.blade.php
<aside class="control-sidebar control-sidebar-dark">

    <ul class="nav nav-tabs nav-justified control-sidebar-tabs">
        <li class="active">
            <a href="#control-sidebar-settings-tab" data-toggle="tab">
                <i class="fa fa-gears"></i> Settings
            </a>
        </li>
    </ul>

    <div class="tab-content">

        <div class="tab-pane active" id="control-sidebar-settings-tab">


            <p><a href="#" data-toggle="control-sidebar">Collapse</a></p>

            <h3 class="control-sidebar-heading">General Settings</h3>

            <div class="form-group">
                <label class="control-sidebar-subheading">
                    <a class="white" href="{{ route('admin.settings.roles') }}">User Roles</a>
                </label>
                <small>Create / Update user roles.</small>
            </div>

            <div class="form-group">
                <label class="control-sidebar-subheading">
                    <a class="white" href="{{ route('admin.settings.permissions') }}">User Permissions</a>
                </label>
                <small>Create / Update user permissions.</small>
            </div>

            <div class="form-group">
                <label class="control-sidebar-subheading">
                    <a class="white" href="{{ route('admin.settings.status') }}">Status</a>
                </label>
                <small>Create / Update Statuses.</small>
            </div>

            <div class="form-group">
                <label class="control-sidebar-subheading">
                    <a class="white" href="{{ route('admin.settings.colours') }}">Colours</a>
                </label>
                <small>Create / Update Colours.</small>
            </div>

            <div class="form-group">
                <label class="control-sidebar-subheading">
                    <a class="white" href="{{ route('admin.settings.insurances') }}">Insurance</a>
                </label>
                <small>Create / Update Insurance.</small>
            </div>

        </div>

    </div>

</aside>